#!/usr/bin/env bash

# create_bridge br0 192.168.64.1/24
setup_bridge() {
    ip link add "${ifname}" type bridge
    ip link set "${ifname}" up
    ip addr add "${ip_interface}" dev "${ifname}"
}

setup_acl() {
    local conf=/etc/qemu/bridge.conf
    touch "${conf}"
    grep "^allow ${ifname}$" "${conf}" ||
        sed -i "\$a allow ${ifname}" "${conf}"
}

setup_nat() {
    # TODO: add more rules
    iptables -t nat -C POSTROUTING -s "${ip_interface}" ! -d "${ip_interface}" -j MASQUERADE &>/dev/null ||
        iptables -t nat -A POSTROUTING -s "${ip_interface}" ! -d "${ip_interface}" -j MASQUERADE
}

setup_dnsmasq() {
    local confd=/etc/vm
    local conf=${confd}/${ifname}
    local ip_prefix=${ip_interface%.*}
    local range_start=${ip_prefix}.2
    local range_end=${ip_prefix}.254

    [[ -d ${confd} ]] || mkdir "${confd}"

    cat <<EOF >"${conf}"
strict-order
pid-file=/run/vm-dnsmasq.pid
except-interface=lo
bind-dynamic
interface=vmbr0
dhcp-range=${range_start},${range_end}
dhcp-no-override
dhcp-authoritative
dhcp-lease-max=253
dhcp-leasefile=/tmp/dhcp.leases
dhcp-hostsfile=/run/vm-default.hostsfile
addn-hosts=/run/vm-default.addnhosts
domain=vm
server=/vm/
EOF

    dnsmasq --conf-file="${conf}"
}

create_net() {
    setup_bridge
    setup_acl
    setup_nat
    setup_dnsmasq
}

main() {
    local ifname=${1}
    local ip_interface=${2}
    create_net
}

main "$@"
