# -*- mode: ruby -*-
# vi: set ft=ruby :

ip_prefix = "192.168.56"

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  config.vm.box = "debian/bookworm64"

  config.vm.define :controller do |controller|
    controller.vm.network :private_network, :ip => "#{ip_prefix}.100"
    controller.vm.hostname = "controller"
  end

  (1..3).each do |i|
    name = "node#{i}"
    ip = "#{ip_prefix}.10#{i}"
    config.vm.define name do |machine|
      machine.vm.network :private_network, :ip => ip
      machine.vm.hostname = name
    end
  end

  config.vm.provision :shell, inline: <<-SHELL
      sed -Ei 's@(https?://)(.+)\\.debian\\.org/@\\1mirrors.ustc.edu.cn/@g' /etc/apt/sources.list
      apt-get update
      which socat || apt-get install -y socat
      which jq || apt-get install -y jq
  SHELL

end
