# -*- mode: ruby -*-
# vi: set ft=ruby :

ip_prefix = "192.168.56"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provision :shell, inline: <<-SHELL
      sed -Ei 's@(https?://)(.+)\\.debian\\.org/@\\1mirrors.ustc.edu.cn/@g' /etc/apt/sources.list
      apt-get update
      which socat || apt-get install -y socat
      which jq || apt-get install -y jq
      sudo cp /vagrant/duck-etcd/etcd* /vagrant/flanneld /usr/local/bin/
  SHELL

  config.vm.define :etcd do |etcd|
    etcd.vm.network :private_network, :ip => "#{ip_prefix}.60"
    etcd.vm.hostname = "etcd"
    etcd.vm.provision :shell, inline: <<-SHELL
      systemd-run etcd
    SHELL
  end

  (1..3).each do |i|
    name = "node#{i}"
    ip = "#{ip_prefix}.6#{i}"
    config.vm.define name do |node|
      node.vm.network :private_network, :ip => ip
      node.vm.hostname = name
      etcd.vm.provision :shell, inline: <<-SHELL
        systemd-run flanneld run 10.244.#{i}
      SHELL
    end
  end
end
