#!/usr/bin/env bash

set -euo pipefail

port=2379

usage() {
    echo >&2 "Usage: $(basename "$0") [-p/--port PORT]"
    exit 1
}

parse_args() {
    while (($#)); do
        case ${1} in
        -p | --port)
            port=${2}
            shift 2
            ;;
        *) usage ;;
        esac
    done
}

main() {
    parse_args "$@"

    socat tcp-l:"${port}",fork,reuseaddr exec:./handler.sh,nofork,fdin=10,fdout=11
}

main "$@"
