#!/usr/bin/env bash

set -o pipefail

server_addr=127.0.0.1:2379

usage() {
    local name
    name=$(basename "$0")

    cat >&2 <<EOF
Usage: ${name} [global options] {put,del,get,watch} [options] [key] [value]

Global Options:
    -s/--server addr, default 127.0.0.1:2379

Examples:
    ${name} put key value
    ${name} del key
    ${name} get [--prefix] [--rev 0] key
    ${name} watch [--prefix] [--rev 0] key
EOF

    exit 1
}

request() {
    local fifo
    fifo=$(mktemp --dry-run)
    mkfifo "${fifo}"
    exec 3<>"${fifo}"
    rm -f "${fifo}"

    socat tcp:"${server_addr}" - <&3 &
    socat_pid=$!

    echo "${msg}" >&3

    wait $socat_pid
}

parse_args() {
    rev=0 prefix=0
    local -a positions

    while (($#)); do
        case ${1} in
        -s | --server)
            server_addr=${2}
            shift 2
            ;;
        --rev)
            rev=${2}
            shift 2
            ;;
        --prefix)
            prefix=1
            shift
            ;;
        -h | --help) usage ;;
        -*)
            echo >&2 "unknown flag: '${1}'"
            usage
            ;;
        *)
            positions+=("${1}")
            shift
            ;;
        esac
    done

    action=${positions[0]}
    key=${positions[1]}
    value=${positions[2]}
}

main() {
    parse_args "$@"

    case $action in
    put)
        # TODO: better to be quoted
        msg="put ${key} ${value}"
        ;;
    del)
        msg="del ${key}"
        ;;
    get | watch)
        msg="rev=${rev} prefix=${prefix} ${action} ${key}"
        ;;
    *) usage ;;
    esac

    request
}

main "$@"
