#!/usr/bin/env bash

set -o pipefail

server_addr=127.0.0.1:2379

req() {
    local fifo
    fifo=$(mktemp --dry-run)
    mkfifo "${fifo}"
    exec 3<>"${fifo}"
    rm -f "${fifo}"

    socat tcp:"${server_addr}" - <&3 &
    socat_pid=$!

    echo "${msg}" >&3

    wait $socat_pid
}

parse_args() {
    rev=0 prefix=0
    while (($#)); do
        case ${1} in
        --rev)
            rev=$2
            shift 2
            ;;
        --prefix)
            prefix=1
            shift
            ;;
        -*)
            echo >&2 "unknown flag: '${1}'"
            ;;
        *) ;;
        esac
    done
}

main() {
    action=${1}
    shift
    case $action in
    put)
        key=${1}
        value=${2}
        # TODO: better to be quoted
        msg="put ${key} ${value}"
        ;;
    del)
        key=${1}
        msg="del ${key}"
        ;;
    get | watch)
        key=${1}
        shift
        parse_args "$@"
        msg="rev=${rev} prefix=${prefix} ${action} ${key}"
        ;;
    *) ;;
    esac

    req
}

main "$@"
